### ISSUE TITLE
xml.sax._exceptions.SAXReaderNotAvailable: No parsers found

### ISSUE THREAD

**Issue by DeadlyFugu** [SublimeText/AAAPackageDev#48] opened 2014-09-11 13:32 UTC
I am unable to convert a plist to yaml using your plugin. 'Convert to YAML and Rearrange Syntax Definition' outputs the following:

    Input type not specified, auto-detecting... Property List
    
    Parsing Property List... (/home/matt/.config/sublime-text-2/Packages/Fruity/Fruity.tmLanguage)

No other messages appear anywhere, nothing happens.

**Comment by FichteFoll** [comment] 2016-01-23 02:22
I'll declare this as an issue with your machine setup, notably involving:

- ST2 (because that refers to the system Python on UNIX, ST3 does not)
- Ubuntu with an incomplete Python setup

In fact, this seems to be an exact duplicate of #34 and reinstalling Python 2.6 seems to be able to solve this. But ST3 works anyway and everyone should be using it.

**Closed** 2016-01-23 02:24 UTC
Labels: duplicate
