### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by ahmedhassan-eng** [SublimeText/AAAPackageDev#58] opened 2015-05-16 13:03 UTC
I recently converted the C Improved language into YAML using AAAPackageDev and found out some highlighting issues.
I'm reporting this because you mentioned you can't fix what you don't know.

And thanks for an amazing tool, buddy!

![cimpyaml](https://cloud.githubusercontent.com/assets/1659721/7666219/e6a867ce-fbe4-11e4-989d-ee2f0eb54015.png)

**Comment by FichteFoll** [comment] 2015-05-17 22:42
Thanks for the report. Next time, please paste the breaking code into the bug report so we can reproduce more easily (for this issue I'll manually convert https://github.com/abusalimov/SublimeCImproved/blob/master/C%20Improved.tmLanguage).

**Comment by FichteFoll** [comment] 2015-07-13 14:06
I fixed one half of the issue above.

The other half of the issue is that this pattern gets converted into a double-quoted scalar in YAML which uses escape mechanisms that the regex doesn't cover (and would be hard to do so). Basically `"\\("` is equivalent to `\(`, but because the `\\` is consumed by the string to be turned into a single literal backslash, the following opening parentheses is matched as a group, even though it is not.

Instead, I will tweak the importing (mainly rearranging) command to dedent leading spaces like the tabs in the example, which I expect to be causing the use of a double-quoted scalar by the dumper.

**Closed** 2015-07-13 16:26 UTC

**Comment by FichteFoll** [comment] 2015-07-13 16:29
Unfortunately the C Improved syntax definition contained a lot of mixed spaces indentation and YAML doesn't play well with tabs after newlines in block scalars, which is what caused the bad conversion.

The proper workflow is as follows:
1. Open `C Improved.tmLanguage` in ST
2. Convert indentation to spaces (using *Indentation: Convert to Spaces* command)
3. Run *AAAPackageDev: Convert to YAML and Rearrange Syntax Definition*

I also added this in to readme, notably the indentation conversion.
